FROM oven/bun

WORKDIR /app

COPY package*.json ./

RUN bun install

COPY ./src ./src    
COPY ./public ./public
COPY next.config.js ./next.config.js
COPY postcss.config.js ./postcss.config.js
COPY tailwind.config.js ./tailwind.config.js
COPY next-env.d.ts ./next-env.d.ts
COPY tsconfig.json ./tsconfig.json 
COPY .env.local ./.env.local
COPY .env.production ./.env.production
COPY .env.development ./.env.development

RUN npm run build

EXPOSE 3000

CMD ["bun", "start"]